apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-a-deployment
    # run: service-a-deployment
  name: service-a-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a-deployment
  template:
    metadata:
      labels:
        app: service-a-deployment
    spec:
      containers:
      - image: akhilmittal510/service-a:latest
        name: service-a
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector.tracing:14268/api/traces"
        - name: SERVICE_B_URI
          value: "http://b-service"
